# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    scan(scheme: "petsTests",
         devices: "iPhone 11")
  end
  
  desc "Take screenshots"
  lane :screenshots do
    snapshot()
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    swiftlint()
    increment_build_number(xcodeproj: "pets.xcodeproj")
    build_app(scheme: "pets")
    upload_to_testflight
  end

end
